### ISSUE TITLE
Wrong `id`s in tibble

### ISSUE THREAD

**Issue by joon-e** [kasperwelbers/twitterAcademic#1]
Dear Kasper,

thank you very much for this wrapper package, which is my current favorite out of all the Academic API wrappers. However, there's one nasty bug right now which leads to incorrect tweet ids (and conversation ids) in the result tibble, as they are read as numeric from the CSV files, but double precision is not precise enough for some longer tweet ids:

```
d1 <- twitter_archive_search("from:nytimes", start_time = "2020-01-01", end_time = "2020-01-02")

ids_1 <- d1 %>% 
  pull(id) %>% 
  as.character()

d2 <- read_csv("twitterAcademicData/fromnytimes_2020-01-01_2020-01-02_finished.csv", col_types = list(id = col_character()))

ids_2 <- d2 %>% 
  pull(id)

all.equal(ids_1, ids_2)
```
```
[1] "79 string mismatches"
```

One simple fix would be to change line 118 in `api.R` from
```
  if (!just_download) readr::read_csv(finished_csv_file, col_types=readr::cols())
```
to
```
  if (!just_download) readr::read_csv(finished_csv_file, col_types=list(id=col_character(), conversation_id=col_character())
```

Best regards

Julian

**Comment by kasperwelbers** [comment]
Owh, that's pretty bad, thanks for catching this! 

I've implemented your suggestion (also at other places where read_csv is used). At some point I should probably check the other fields to set standard column types. 

Best,
Kasper
