### ISSUE TITLE
Error - non-ok status code: 403

### ISSUE THREAD

**Issue by andersolarsson** [kasperwelbers/twitterAcademic#2]
Hello,

Great  idea for a package! I have been trying the following:

```
Ap_2021 <- 
  twitter_archive_search(query = "from:Arbeiderpartiet",
                         start_time = "2021-01-01",
                         end_time = "2021-12-31",
                         progressbar = TRUE)
```
… wanting to get  tweets from @Arbeiderpartiet without succeeding - here  is the error message:

`Something went wrong! Got this non-ok status code here: 403. For now we'll just wait a few seconds and try again, but if this keeps failing let me know Error in if (page$meta$result_count > 0) { : argument is of length zero`

Any suggestions regarding what I might be  doing wrong would be most helpful.

Best,
Anders

**Comment by andersolarsson** [comment]
Hello again - never mind, there seems to have been a temporary issue. Everything seems to be working now, thanks again!

**Comment by kasperwelbers** [comment]
Hi @andersolarsson,

Great that it worked for you. Just wanted to mention that by now there is a more established package for using the Academic Twitter API: [academictwitteR](https://cran.r-project.org/web/packages/academictwitteR/index.html)

Our package was mainly an ad-hoc solution, and while it works for simple cases, for the long run and more features we'd definitely recommend academictwitteR.

Best,
Kasper

**Comment by andersolarsson** [comment]
Hello again,

Thank you! yes, academictwitteR I find works nicely for a lot of operations but twitterAcademic is really nice for simpler tasks, like the kinds of calls I tried above.

Best,
Anders
